name: perfmon-lighthouse-api
region: nyc

services:
  - name: lighthouse-api
    github:
      repo: papayaah/perfmon
      branch: master
      deploy_on_push: false
    dockerfile_path: Dockerfile
    source_dir: /
    
    instance_count: 1
    instance_size_slug: basic-xs
    
    http_port: 8080
    
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: MAX_CONCURRENT_ANALYSES
        value: "1"
      - key: MAX_QUEUE_SIZE
        value: "10"
      - key: QUEUE_TIMEOUT_MS
        value: "120000"
      # Note: stats.json will reset on each deploy without persistent storage
      # For production, consider using DigitalOcean Managed Database (PostgreSQL)
      # or Redis to persist statistics across deployments
    
    health_check:
      http_path: /health
    
    routes:
      - path: /api
